{{- template "comment" . -}}
name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v3
        with:
          go-version: {{`${{ env.GO_VERSION }}`}}

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: {{`${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}`}}
          restore-keys: |
            {{`${{ runner.os }}-go-`}}

      - name: Run tests
        run: make test
{{ if .Values.codeclimate.enabled }}
      - name: Upload code coverage report to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: {{ .Values.codeclimate.reporterID }}
        with:
          coverageLocations: cover.out:gocov
          prefix: {{`github.com/${{ github.repository }}`}}
{{- end -}}
{{ if .Values.codecov.enabled }}
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./cover.out
{{- end }}
{{ if .Values.goreport.enabled}}
      - name: Trigger goreport refresh
        uses: creekorful/goreportcard-action@v1.0
{{- end }}
